In QuickDirtyStaticGitWebCli I used a "scoped result emitter" for the first time. It guarantees that even if exceptions are thrown, the result still gets emitted. But it makes me wonder, what if in your "at scoped end" action also throws an exception? Can two exceptions be thrown at once? My brain hurts (I never use exceptions, I like knowing whether or not an op succeeded via a simple bool).